FROM debian:bookworm-slim

ARG TARGETARCH

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY bin/${TARGETARCH}/oxi-hole /usr/local/bin/oxi-hole
COPY config.toml /etc/oxi-hole/config.toml

RUN chmod 755 /usr/local/bin/oxi-hole

EXPOSE 53/udp 53/tcp 853/tcp 443/tcp 8080/tcp

ENTRYPOINT ["oxi-hole", "/etc/oxi-hole/config.toml"]
